<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['code' => 'AF', 'description' => 'Afghanistan'],
            ['code' => 'AL', 'description' => 'Albania'],
            ['code' => 'DZ', 'description' => 'Algeria'],
            ['code' => 'AS', 'description' => 'American Samoa'],
            ['code' => 'AD', 'description' => 'Andorra'],
            ['code' => 'AO', 'description' => 'Angola'],
            ['code' => 'AI', 'description' => 'Anguilla'],
            ['code' => 'AQ', 'description' => 'Antarctica'],
            ['code' => 'AG', 'description' => 'Antigua and Barbuda'],
            ['code' => 'AR', 'description' => 'Argentina'],
            ['code' => 'AM', 'description' => 'Armenia'],
            ['code' => 'AW', 'description' => 'Aruba'],
            ['code' => 'AU', 'description' => 'Australia'],
            ['code' => 'AT', 'description' => 'Austria'],
            ['code' => 'AZ', 'description' => 'Azerbaijan'],
            ['code' => 'BS', 'description' => 'Bahamas'],
            ['code' => 'BH', 'description' => 'Bahrain'],
            ['code' => 'BD', 'description' => 'Bangladesh'],
            ['code' => 'BB', 'description' => 'Barbados'],
            ['code' => 'BY', 'description' => 'Belarus'],
            ['code' => 'BE', 'description' => 'Belgium'],
            ['code' => 'BZ', 'description' => 'Belize'],
            ['code' => 'BJ', 'description' => 'Benin'],
            ['code' => 'BM', 'description' => 'Bermuda'],
            ['code' => 'BT', 'description' => 'Bhutan'],
            ['code' => 'BO', 'description' => 'Bolivia'],
            ['code' => 'BA', 'description' => 'Bosnia and Herzegovina'],
            ['code' => 'BW', 'description' => 'Botswana'],
            ['code' => 'BR', 'description' => 'Brazil'],
            ['code' => 'IO', 'description' => 'British Indian Ocean Territory'],
            ['code' => 'BN', 'description' => 'Brunei Darussalam'],
            ['code' => 'BG', 'description' => 'Bulgaria'],
            ['code' => 'BF', 'description' => 'Burkina Faso'],
            ['code' => 'BI', 'description' => 'Burundi'],
            ['code' => 'CV', 'description' => 'Cabo Verde'],
            ['code' => 'KH', 'description' => 'Cambodia'],
            ['code' => 'CM', 'description' => 'Cameroon'],
            ['code' => 'CA', 'description' => 'Canada'],
            ['code' => 'KY', 'description' => 'Cayman Islands'],
            ['code' => 'CF', 'description' => 'Central African Republic'],
            ['code' => 'TD', 'description' => 'Chad'],
            ['code' => 'CL', 'description' => 'Chile'],
            ['code' => 'CN', 'description' => 'China'],
            ['code' => 'CO', 'description' => 'Colombia'],
            ['code' => 'KM', 'description' => 'Comoros'],
            ['code' => 'CG', 'description' => 'Congo'],
            ['code' => 'CD', 'description' => 'Congo (Democratic Republic)'],
            ['code' => 'CK', 'description' => 'Cook Islands'],
            ['code' => 'CR', 'description' => 'Costa Rica'],
            ['code' => 'HR', 'description' => 'Croatia'],
            ['code' => 'CU', 'description' => 'Cuba'],
            ['code' => 'CY', 'description' => 'Cyprus'],
            ['code' => 'CZ', 'description' => 'Czech Republic'],
            ['code' => 'DK', 'description' => 'Denmark'],
            ['code' => 'DJ', 'description' => 'Djibouti'],
            ['code' => 'DM', 'description' => 'Dominica'],
            ['code' => 'DO', 'description' => 'Dominican Republic'],
            ['code' => 'EC', 'description' => 'Ecuador'],
            ['code' => 'EG', 'description' => 'Egypt'],
            ['code' => 'SV', 'description' => 'El Salvador'],
            ['code' => 'GQ', 'description' => 'Equatorial Guinea'],
            ['code' => 'ER', 'description' => 'Eritrea'],
            ['code' => 'EE', 'description' => 'Estonia'],
            ['code' => 'SZ', 'description' => 'Eswatini'],
            ['code' => 'ET', 'description' => 'Ethiopia'],
            ['code' => 'FJ', 'description' => 'Fiji'],
            ['code' => 'FI', 'description' => 'Finland'],
            ['code' => 'FR', 'description' => 'France'],
            ['code' => 'GA', 'description' => 'Gabon'],
            ['code' => 'GM', 'description' => 'Gambia'],
            ['code' => 'GE', 'description' => 'Georgia'],
            ['code' => 'DE', 'description' => 'Germany'],
            ['code' => 'GH', 'description' => 'Ghana'],
            ['code' => 'GR', 'description' => 'Greece'],
            ['code' => 'GD', 'description' => 'Grenada'],
            ['code' => 'GU', 'description' => 'Guam'],
            ['code' => 'GT', 'description' => 'Guatemala'],
            ['code' => 'GN', 'description' => 'Guinea'],
            ['code' => 'GW', 'description' => 'Guinea-Bissau'],
            ['code' => 'GY', 'description' => 'Guyana'],
            ['code' => 'HT', 'description' => 'Haiti'],
            ['code' => 'HN', 'description' => 'Honduras'],
            ['code' => 'HK', 'description' => 'Hong Kong'],
            ['code' => 'HU', 'description' => 'Hungary'],
            ['code' => 'IS', 'description' => 'Iceland'],
            ['code' => 'IN', 'description' => 'India'],
            ['code' => 'ID', 'description' => 'Indonesia'],
            ['code' => 'IR', 'description' => 'Iran'],
            ['code' => 'IQ', 'description' => 'Iraq'],
            ['code' => 'IE', 'description' => 'Ireland'],
            ['code' => 'IL', 'description' => 'Israel'],
            ['code' => 'IT', 'description' => 'Italy'],
            ['code' => 'JM', 'description' => 'Jamaica'],
            ['code' => 'JP', 'description' => 'Japan'],
            ['code' => 'JO', 'description' => 'Jordan'],
            ['code' => 'KZ', 'description' => 'Kazakhstan'],
            ['code' => 'KE', 'description' => 'Kenya'],
            ['code' => 'KI', 'description' => 'Kiribati'],
            ['code' => 'KP', 'description' => 'Korea (North)'],
            ['code' => 'KR', 'description' => 'Korea (South)'],
            ['code' => 'KW', 'description' => 'Kuwait'],
            ['code' => 'KG', 'description' => 'Kyrgyzstan'],
            ['code' => 'LA', 'description' => 'Laos'],
            ['code' => 'LV', 'description' => 'Latvia'],
            ['code' => 'LB', 'description' => 'Lebanon'],
            ['code' => 'LS', 'description' => 'Lesotho'],
            ['code' => 'LR', 'description' => 'Liberia'],
            ['code' => 'LY', 'description' => 'Libya'],
            ['code' => 'LI', 'description' => 'Liechtenstein'],
            ['code' => 'LT', 'description' => 'Lithuania'],
            ['code' => 'LU', 'description' => 'Luxembourg'],
            ['code' => 'MG', 'description' => 'Madagascar'],
            ['code' => 'MW', 'description' => 'Malawi'],
            ['code' => 'MY', 'description' => 'Malaysia'],
            ['code' => 'MV', 'description' => 'Maldives'],
            ['code' => 'ML', 'description' => 'Mali'],
            ['code' => 'MT', 'description' => 'Malta'],
            ['code' => 'MH', 'description' => 'Marshall Islands'],
            ['code' => 'MR', 'description' => 'Mauritania'],
            ['code' => 'MU', 'description' => 'Mauritius'],
            ['code' => 'MX', 'description' => 'Mexico'],
            ['code' => 'FM', 'description' => 'Micronesia (Federated States of)'],
            ['code' => 'MD', 'description' => 'Moldova'],
            ['code' => 'MC', 'description' => 'Monaco'],
            ['code' => 'MN', 'description' => 'Mongolia'],
            ['code' => 'ME', 'description' => 'Montenegro'],
            ['code' => 'MA', 'description' => 'Morocco'],
            ['code' => 'MZ', 'description' => 'Mozambique'],
            ['code' => 'MM', 'description' => 'Myanmar'],
            ['code' => 'NA', 'description' => 'Namibia'],
            ['code' => 'NR', 'description' => 'Nauru'],
            ['code' => 'NP', 'description' => 'Nepal'],
            ['code' => 'NL', 'description' => 'Netherlands'],
            ['code' => 'NZ', 'description' => 'New Zealand'],
            ['code' => 'NI', 'description' => 'Nicaragua'],
            ['code' => 'NE', 'description' => 'Niger'],
            ['code' => 'NG', 'description' => 'Nigeria'],
            ['code' => 'NO', 'description' => 'Norway'],
            ['code' => 'OM', 'description' => 'Oman'],
            ['code' => 'PK', 'description' => 'Pakistan'],
            ['code' => 'PW', 'description' => 'Palau'],
            ['code' => 'PS', 'description' => 'Palestine'],
            ['code' => 'PA', 'description' => 'Panama'],
            ['code' => 'PG', 'description' => 'Papua New Guinea'],
            ['code' => 'PY', 'description' => 'Paraguay'],
            ['code' => 'PE', 'description' => 'Peru'],
            ['code' => 'PH', 'description' => 'Philippines'],
            ['code' => 'PL', 'description' => 'Poland'],
            ['code' => 'PT', 'description' => 'Portugal'],
            ['code' => 'QA', 'description' => 'Qatar'],
            ['code' => 'RO', 'description' => 'Romania'],
            ['code' => 'RU', 'description' => 'Russia'],
            ['code' => 'RW', 'description' => 'Rwanda'],
            ['code' => 'KN', 'description' => 'Saint Kitts and Nevis'],
            ['code' => 'LC', 'description' => 'Saint Lucia'],
            ['code' => 'VC', 'description' => 'Saint Vincent and the Grenadines'],
            ['code' => 'WS', 'description' => 'Samoa'],
            ['code' => 'SM', 'description' => 'San Marino'],
            ['code' => 'ST', 'description' => 'Sao Tome and Principe'],
            ['code' => 'SA', 'description' => 'Saudi Arabia'],
            ['code' => 'SN', 'description' => 'Senegal'],
            ['code' => 'RS', 'description' => 'Serbia'],
            ['code' => 'SC', 'description' => 'Seychelles'],
            ['code' => 'SL', 'description' => 'Sierra Leone'],
            ['code' => 'SG', 'description' => 'Singapore'],
            ['code' => 'SK', 'description' => 'Slovakia'],
            ['code' => 'SI', 'description' => 'Slovenia'],
            ['code' => 'SB', 'description' => 'Solomon Islands'],
            ['code' => 'SO', 'description' => 'Somalia'],
            ['code' => 'ZA', 'description' => 'South Africa'],
            ['code' => 'SS', 'description' => 'South Sudan'],
            ['code' => 'ES', 'description' => 'Spain'],
            ['code' => 'LK', 'description' => 'Sri Lanka'],
            ['code' => 'SD', 'description' => 'Sudan'],
            ['code' => 'SR', 'description' => 'Suriname'],
            ['code' => 'SE', 'description' => 'Sweden'],
            ['code' => 'CH', 'description' => 'Switzerland'],
            ['code' => 'SY', 'description' => 'Syria'],
            ['code' => 'TW', 'description' => 'Taiwan'],
            ['code' => 'TJ', 'description' => 'Tajikistan'],
            ['code' => 'TZ', 'description' => 'Tanzania'],
            ['code' => 'TH', 'description' => 'Thailand'],
            ['code' => 'TL', 'description' => 'Timor-Leste'],
            ['code' => 'TG', 'description' => 'Togo'],
            ['code' => 'TO', 'description' => 'Tonga'],
            ['code' => 'TT', 'description' => 'Trinidad and Tobago'],
            ['code' => 'TN', 'description' => 'Tunisia'],
            ['code' => 'TR', 'description' => 'Turkey'],
            ['code' => 'TM', 'description' => 'Turkmenistan'],
            ['code' => 'TV', 'description' => 'Tuvalu'],
            ['code' => 'UG', 'description' => 'Uganda'],
            ['code' => 'UA', 'description' => 'Ukraine'],
            ['code' => 'AE', 'description' => 'United Arab Emirates'],
            ['code' => 'GB', 'description' => 'United Kingdom'],
            ['code' => 'US', 'description' => 'United States'],
            ['code' => 'UY', 'description' => 'Uruguay'],
            ['code' => 'UZ', 'description' => 'Uzbekistan'],
            ['code' => 'VU', 'description' => 'Vanuatu'],
            ['code' => 'VE', 'description' => 'Venezuela'],
            ['code' => 'VN', 'description' => 'Vietnam'],
            ['code' => 'YE', 'description' => 'Yemen'],
            ['code' => 'ZM', 'description' => 'Zambia'],
            ['code' => 'ZW', 'description' => 'Zimbabwe'],
        ];

        foreach ($data as $country) {
            Country::updateOrCreate(['code' => $country['code']], ['description' => $country['description']]);
        }
    }
}
