<?php

namespace Database\Seeders;

use App\Models\CurrentPosition;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CurrentPostionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $positions =[
            'Able Seaman',
            'Account Associate',
            'Account Manager',
            'Account Processor Documentation',
            'Account Representative',
            'Account Specialist',
            'Account Specialist I',
            'Accountant',
            'Accounting Director',
            'Accounting Staff/Assistant',
            'Accounts Payable Clerk',
            'Accounts Receivable Clerk',
            'Actuary',
            'Admin Aide III',
            'Administrative Assistant',
            'Administrative Coordinator',
            'Administrative Officer',
            'Administrative Services Aide',
            'Administrative Staff/Assistant',
            'Administrator',
            'Aesthetic Nurse',
            'Aesthetician',
            'Analyst',
            'Arbitrator',
            'Area Supervisor',
            'Assistant Manager',
            'Assistant Restaurant Manager',
            'Assistant Store Manager',
            'Assistant Supervisor',
            'Assistant To The Hospital Administrator',
            'Audio Visual',
            'Auditor',
            'Auto Painting Technician',
            'AutoCAD Draftsman',
            'Aviation Security',
            'Bank Teller',
            'Basic Operator',
            'Beauty Advisor',
            'Benefits Administrator',
            'Bilingual Customer Service Representative',
            'Bill Collector',
            'Bookkeeper',
            'Brand Specialist',
            'Budget Analyst',
            'Building Janitor',
            'Building Maintenance',
            'Bus Driver',
            'Business Development Coordinator',
            'Business Reporter',
            'Butcher',
            'CADD Operator',
            'Call Center Agent',
            'Call Center Customer Support',
            'Caretaker',
            'Carpenter',
            'Case Manager',
            'Cashier',
            'Center Administrative Head',
            'Chapter Service Representative',
            'Chef Cook',
            'Chief Inspectorate',
            'Civil Worker',
            'Cleaner',
            'Client Advisor',
            'Collection Analyst',
            'Collections Agent',
            'Community Expert',
            'Company Driver',
            'Company Guard',
            'Condo Cleaner',
            'Contact Center Associate',
            'Content Manager',
            'Content Moderator',
            'Control Tower Assistant',
            'Controller',
            'Corporate Attorney',
            'Corporate Driver',
            'Customer Care Consultant',
            'Customer Service Representative',
            'Councilor',
            'Credit Analyst',
            'Credit And Collection Assistant',
            'Credit And Collection Manager',
            'Credit And Collection Specialist',
            'Credit And Collection Supervisor',
            'Customer Relationship Coordinator',
            'Customer Service Agent',
            'Customer Service Assistant',
            'Customer Service Associate',
            'Customer Service Manager',
            'Customer Service Officer',
            'Customer Service Specialist',
            'Customer Support Associate',
            'Customer Support Officer',
            'Data Analyst',
            'Data Encoder',
            'Data Process Support Team Lead',
            'Delivery Helper/Rider',
            'Detachment Commander',
            'Dispatcher/Utility',
            'Domestic Helper',
            'Electrical Maintenance',
            'Electrician',
            'Embalmer',
            'Engineering Maintenance Augment',
            'Engineering Officer',
            'Executive',
            'Executive Assistant',
            'Executive Customer Service Representative',
            'Executive Office Secretary',
            'Executive Operations',
            'Facilities Coordinator',
            'Factory Worker',
            'Faculty Staff',
            'Family Driver',
            'Field Merchandising Supervisor',
            'Field Supervisor',
            'File Clerk',
            'Finance Specialist',
            'Financial Analyst',
            'Financial Planner',
            'Foreman',
            'Forklift Operator',
            'General Counsel',
            'General Foreman Mechanical',
            'Head Of Operations',
            'Head Pastor',
            'Heavy Equipment Operator',
            'Help Desk Coordinator',
            'Household Service Worker',
            'Housekeeping Attendant',
            'Housekeeping Staff',
            'Housemaid',
            'Houseman',
            'Human Resource Assistant',
            'Human Resource Manager',
            'Human Resource Officer',
            'Installer',
            'Instructor',
            'Investment Banking Analyst',
            'IT Manager',
            'IT Operations Associate',
            'IT Staff Personnel',
            'IT Supervisor',
            'Janitorial',
            'Junior Sales Assistant',
            'Junior Tax Associate',
            'Kitchen Helper',
            'Kitchen Staff',
            'Kitchen Supervisor',
            'Labor General',
            'Laboratory Technician',
            'Legal Aide',
            'Legal Analyst',
            'Legal Assistant',
            'Legal Consultant',
            'Legal Secretary',
            'Liason Officer',
            'Lineman',
            'Liner Clerk',
            'Local Legislative Staff Officer III',
            'Logistics Assistant Manager',
            'Logistics Staff',
            'Machine Operator Staff',
            'Maintenance Technician',
            'Manager',
            'Manufacturing Crew',
            'Marketing Assistant',
            'Marketing Manager',
            'Massage Therapist',
            'Master Teacher 1',
            'Mechanic',
            'Mediator',
            'Medical Documentation Associate',
            'Messenger',
            'Midwife I',
            'Network Operations Engineer',
            'Nursing Attendant',
            'Office Housekeeper',
            'Office Staff/Clerk',
            'Office Support Staff',
            'Officer',
            'Operation Assistant/Staff',
            'Operation Manager',
            'Operations Analyst',
            'Operations Personnel',
            'Operator',
            'Patrol Man',
            'Payroll Analyst',
            'Payroll Assistant',
            'Payroll Manager',
            'Pharmacist Assistant',
            'Planning Officer II',
            'Plumber',
            'President',
            'Principal',
            'Process Analyst',
            'Process Associate',
            'Procurement Assistant',
            'Procurement Specialist',
            'Product Manager',
            'Product Promoter',
            'Production Finisher',
            'Production Operator',
            'Program Administrator',
            'Program Manager',
            'Program Officer',
            'Project Coordinator',
            'Project Engineer',
            'Public Area Attendant',
            'QC Supervisor',
            'Quality Assurance Auditor',
            'Quality Assurance Specialist',
            'Quality Control Assistant',
            'Quality Control Supervisor',
            'Quality Control Technician',
            'Receptionist',
            'Record Assistant',
            'Refrigeration Technician',
            'Regulatory Assistant',
            'Risk Manager',
            'Safety Officer',
            'Safety Supervisor',
            'Sales Advisor 1',
            'Sales Agent',
            'Sales And Marketing Staff',
            'Sales Clerk/Staff',
            'Sales Consultant',
            'Sales Coordinator',
            'Sales Manager',
            'Sales Promoter',
            'Sales Supervisor',
            'Sales Support Staff',
            'Salesman',
            'School Driver',
            'Seaman',
            'Secretary',
            'Security Officer',
            'Security Personnel',
            'Senior Account Officer',
            'Senior Crew',
            'Senior Logistics Coordinator',
            'Senior Sales Associate',
            'Senior Stylist',
            'Senior Technical Advisor',
            'Service Analyst',
            'Service Coordinator',
            'Service Crew',
            'Service Officer',
            'Service Operations Technician',
            'Service Technician',
            'Site Finance Representative',
            'Sports Data Analyst',
            'Sprinter',
            'Staff Assistant',
            'Staff Midwife',
            'Staff Nurse',
            'Steelman',
            'Stock Custodian',
            'Stockman',
            'Store Keeper',
            'Supervisor',
            'Surveillance Operator',
            'Teacher',
            'Teacher 1',
            'Teacher 1B',
            'Teacher II',
            'Teacher III',
            'Teacher/Faculty',
            'Team Captain',
            'Team Leader',
            'Technical Engineer',
            'Technical Field Engineer',
            'Technical Intern',
            'Technical Support Operations',
            'Technical Support Representative',
            'Technical Support Specialist',
            'Technician',
            'Telemarketer',
            'Teleservices Representative',
            'Time Keeper',
            'Treasury Assistant',
            'Utility Officer',
            'Utility Worker II',
            'Vice President',
            'Village Manager',
            'Waiter',
            'Warehouse Assistant/Staff',
            'Warehouse Supervisor',
            'Welder'
        ];
        foreach ($positions as $index => $p) {
            CurrentPosition::updateOrCreate(['code' => str_pad($index + 1, 3, '0', STR_PAD_LEFT)], ['description' => $p]);
        }
    }
}
